### ISSUE TITLE
Why Astro with RR7 - which has Prerender

### ISSUE THREAD

**Issue by isherbuilds** [xanthous-tech/remix-hono-template#1]
Thankyou ❤️  for the best stack ever.

I am just curious on why did we choose astro since with RR7 `Pre-rendering allows you to render pages at build time instead of on a server to speed up pages loads for static content.` 

Pre-rendering allows you to render pages at build time instead of on a server to speed up pages loads for static content.

Is it mainly for the content layer which is really good or any other reason?

Also why redis when we can go dragonfly (supposedly its faster and oss)

P.S: Love the stack

**Comment by lhr0909** [comment]
@itsmegood Hey thank you for the kind words!

The reason behind adding Astro is exactly for the static content building (not just markdown and content layer, but also things like sitemap generation and even documentation pages etc), which will take a lot of custom code in RR7 / vite to catch up with what Astro offers. I have researched a lot on GitHub and couldn't find anything before RR7, and as it lands, there isn't anything I can go off of to speed up the development.

At the moment I desperately need content pages in all of my projects so I took the easier way for now. Astro is quite lightweight so it is easy to take it out if static content is not needed. I am also tempted to see if SSR is really needed, and I might actually make RR7 client side only and nest it inside Astro. It is an option!
